### ISSUE TITLE
Unable to install in Engine or Game

### ISSUE THREAD

**Issue by SJOEC** [JetBrains/UnrealLink#270]
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Unversioned -Plugin=C:\Users\johan\AppData\Local\Temp\UnrealLink\Xahatox\RiderLink.uplugin -Package=C:\Users\johan\AppData\Local\Temp\UnrealLink\Kimiqok
Initializing script modules...
Total script module initialization time: 0.16 s.
Executing commands...
Copying 394 file(s) using max 64 thread(s)
Reading plugin from C:\Users\johan\AppData\Local\Temp\UnrealLink\Kimiqok\HostProject\Plugins\RiderLink\RiderLink.uplugin...
Building plugin for host platforms: Win64
Running: E:\Unreal\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "E:\Unreal\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="C:\Users\johan\AppData\Local\Temp\UnrealLink\Kimiqok\HostProject\HostProject.uproject" -plugin="C:\Users\johan\AppData\Local\Temp\UnrealLink\Kimiqok\HostProject\Plugins\RiderLink\RiderLink.uplugin" -noubtmakefiles -manifest="C:\Users\johan\AppData\Local\Temp\UnrealLink\Kimiqok\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\johan\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\johan\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
Total execution time: 2.64 seconds
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in E:\Unreal\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
Took 2.78s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\johan\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 3s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
Failed to build RiderLink plugin for E:\Unreal\UE_5.3
Failed to build RiderLink plugin

I have my projects in the disk "E:".

**Comment by SJOEC** [comment]
[UBT-UnrealEditor-Win64-Development.txt](https://github.com/JetBrains/UnrealLink/files/13171086/UBT-UnrealEditor-Win64-Development.txt)

here's the log file

**Comment by nikolaipaul** [comment]
Have the same issue

**Comment by DecoyRS** [comment]
Hello folks!
What version of UE are you using? I mean, is it from source, or from Epic Games Launcher?
Logs say that the crash happened in the line that doesn't correspond to the UE 5.3.1 from EGS.
If you have custom Unreal Engine version, would you be so kind as to add logs to `Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs` file.
In `protected void AddAllValidModulesToTarget(ILogger Logger)` function, add
`Logger.LogDebug("Check if {Module} is responsible for crash", ModuleName);`
before 
`if (!ModuleRules.IsValidForTarget(RulesType, Rules, out string? InvalidReason))` line
and share the logs again.

**Comment by nikolaipaul** [comment]
@DecoyRS

I only have this problem when directly trying to open the .uproject with Rider.

- Im using UE 5.3.1
- Its from the Epic Games Launcher

Here is my log with the addition:
[Log_GPF.txt](https://github.com/JetBrains/UnrealLink/files/13278707/Log_GPF.txt)

This is the error Rider is showing:
`11:20:01.038: Log file: C:\Users\Nikolai\AppData\Local\UnrealBuildTool\Log_GPF.txt
11:20:01.126: Some Platforms were skipped due to invalid SDK setup: IOS, Android, Linux, LinuxArm64.
11:20:01.126: See the log file for detailed information
11:20:01.131: Generating Rider project files:
11:20:01.623: Writing project files...
11:20:01.623: Exception while generating include data for Target:UnrealEditor, Platform: Win64, Configuration: Development
11:20:01.632: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
11:20:01.632:    at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
11:20:01.632:    at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
11:20:01.632:    at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
11:20:01.632:    at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
11:20:01.632:    at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
11:20:01.632:    at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
11:20:01.632:    at UnrealBuildTool.RiderProjectFile.WriteProjectFile(List`1 InPlatforms, List`1 InConfigurations, PlatformProjectGeneratorCollection PlatformProjectGenerators, JsonWriterStyle Minimize, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\Rider\RiderProjectFile.cs:line 110
11:20:03.282: Writing project files... 100%
`

**Comment by jeffkasunic** [comment]
I'm not sure if we are having the same problem. But I was getting similar error messages, and was able to fix it with these steps:

1. Uninstall Unreal Engine.
2. Uninstall Rider.
3. Install Visual Studio
4. Install Unreal Engine using Visual Studio as the IDE. UE Editor Preferences - Source Code - Visual Studio
5. Made a test C++ project using Visual Studio.
6. Install Rider.

Basically, try uninstalling everything. Reinstall things with Rider being the final step.

**Comment by nikolaipaul** [comment]
> I'm not sure if we are having the same problem. But I was getting similar error messages, and was able to fix it with these steps:
> 
> 1. Uninstall Unreal Engine.
> 2. Uninstall Rider.
> 3. Install Visual Studio
> 4. Install Unreal Engine using Visual Studio as the IDE. UE Editor Preferences - Source Code - Visual Studio
> 5. Made a test C++ project using Visual Studio.
> 6. Install Rider.
> 
> Basically, try uninstalling everything. Reinstall things with Rider being the final step.

Thanks. It did work.

**Comment by edelmeier** [comment]
Thanks for sharing your insights.
I also have the same issue. C'mon...reinstall _everything_? Anyone got an idea how to get rid of this?

**Comment by ImKyra** [comment]
Yeah my trust in Rider for UE developpement is severely rigged, 2 hours lost in this nonsense.

**Comment by linqen** [comment]
Hey, check my answer here:
https://github.com/JetBrains/UnrealLink/issues/278#issuecomment-2085041689

**Comment by bluebright** [comment]
> Hey, check my answer here: [#278 (comment)](https://github.com/JetBrains/UnrealLink/issues/278#issuecomment-2085041689)

Sorry. Not working...

**Comment by linqen** [comment]
Hi @DecoyRS , reinstalling the engine worked to me. In my opinion this is related to changes inside the engine and Rider cached information on AppData. 

The fix I proposed in my comment didn't even lasted for long...

**Comment by knejadfard** [comment]
> Hi @DecoyRS , reinstalling the engine worked to me. In my opinion this is related to changes inside the engine and Rider cached information on AppData.
> 
> The fix I proposed in my comment didn't even lasted for long...

Same here! Reinstalling the 5.4.4 engine worked for me.

**Comment by inspire22** [comment]
I also get this error when trying to use rider (and c++ with unreal in general) for the first time.  Super frustrated after a few days of trying to get this to work messing with versions of visual studio, customizing windows 11 file directory owner settings (why on earth?).  I really didn't want to re download/install the 100GB that is unreal engine 5.5.1 but I'll try it this evening I guess.

Since this is the first time I've ever used Rider, it can't be an issue with caching anything.

**Comment by nwilging** [comment]
+1 to this issue. I've experienced it a few times and in the past it has been a result of different reasons. The most common answer on this from both Epic and Jetbrains is [a bad plugin](https://youtrack.jetbrains.com/issue/RIDER-100275/Exception-while-generating-include-data-for-TargetUnrealEditor-Platform-Win64-Configuration-Development) (usually a broken custom plugin I guess). However in my case, and in many other cases, I dont think this is the only resolution.

In my case I am working on a plugin. It is the only plugin installed in a "template" project I am using to test things out. Everything has been working fine until last night, I began to get errors for "unresolved external symbols" for functions that _definitely_ exist (the ide sees them, I see them, etc). After trying to correct this by deleting `Intermediate`, `Binaries` and `DerivedDataCache` from both the template project and the plugin's folder, I began getting the `Exception while generating include data for Target:UnrealEditor, Platform: Win64, Configuration: Development` error as described in this ticket.

Reinstalling everything will be a last resort for me. I don't see how that is a viable solution, if for instance running `Verify` on the UE installation does not fix the issue (it doesn't -- i've verified twice now). At the moment the only theory I have to go on is that something inside my plugin is misconfigured.

I'm not sure how much I buy that though. I am having the _same_ issues on projects I haven't even touched in weeks/months -- projects that previously were opening, building, and running just fine.

**Comment by nwilging** [comment]
update: i was able to get the editor to run by installing RiderLink directly inside the project (in `Plugins/Developer/RiderLink` -- where rider extracts the plugin when using "Extract Plugin" in settings). Rider still wont' load the project. VisualStudio will load the project and all its plugins and build it without issue. This rules out an issue within the project preventing Rider from indexing it.

going to uninstall and reinstall rider and see if that fixes anything. I definitely stand by the idea that we should not have to install/reinstall UE, nor should there be a particular order that is required to install tools for them to work properly (so long as the tools are designed to operate independently -- exceptions being stuff like compilers obviously).

**Comment by inspire22** [comment]
I did finally get my riderlink to compile - it was definitely a multi-day effort so I'm not sure exactly what did it.  

1) I finally got VS studio 2022 to compile a sample project (using a link I'd found to "pin" it to the older version, not sure if that's necessary).  

2) Then in rider settings I changed the MSBuild version (there were like 8 in the list, I tried a few).  

3) Then I edited the riderlink source code (WTF, right?) as mentioned in this forum thread https://forums.unrealengine.com/t/ubt-bug-no-longer-able-to-compile-plugins-in-standalone-since-5-3/1318659/14

For a lot of folks, looks like that let them figure out the real problem from the logfile (since it shows the error now instead of crashing the build process).  I didn't have any other plugins installed (beside the included unreal ones) and it just started working after that.

**Comment by nwilging** [comment]
I changed the UBT modulerules.cs file according to the thread above, and for whatever reason that just solved all my issues. No extra debugging needed. I have a feeling that may be due to me rebuilding UBT as part of that process. I'm surprised that was caught during UE verification.

If this ever happens again I'll start with just rebuilding UBT

**Comment by alexpad308** [comment]
If you encounter the error Unhandled exception: ArgumentNullException: Value cannot be null. (Parameter 'element'), it indicates that there are unknown modifications in the engine directory (e.g., manually added third-party plugins). First, remove any manually imported third-party plugins from the UE engine, then reinstall the RiderLink plugin and it should be fine to install.

**Comment by Liquidmasl** [comment]
> If you encounter the error Unhandled exception: ArgumentNullException: Value cannot be null. (Parameter 'element'), it indicates that there are unknown modifications in the engine directory (e.g., manually added third-party plugins). First, remove any manually imported third-party plugins from the UE engine, then reinstall the RiderLink plugin and it should be fine to install.

I literalluy just downloaded the engine and tried to get rider link to install.. doesnt work. 
So unsure about the modifications

**Comment by ojingo** [comment]
Second vote for this link - it shows the issue and the workaround / fix. 

https://forums.unrealengine.com/t/ubt-bug-no-longer-able-to-compile-plugins-in-standalone-since-5-3/1318659/14

Us patching our own UBT.dll is probably not the best way to fix it but it's a temporary patch... I would hope someone at Unreal or Jetbrains can coordinate the real fix?

**Comment by Rokukkkk** [comment]
I just found out that my situation was caused by the **VisualStudioTool** inside the Engine/Plugins folder. The plugin is automatically installed by VS if you open a Unreal project.

**Comment by trimination** [comment]
> I just found out that my situation was caused by the **VisualStudioTool** inside the Engine/Plugins folder. The plugin is automatically installed by VS if you open a Unreal project.

This worked for me also, I never properly set up VS2022 with Unreal either so that may have something to do with it.

**Comment by Rokukkkk** [comment]
> > I just found out that my situation was caused by the **VisualStudioTool** inside the Engine/Plugins folder. The plugin is automatically installed by VS if you open a Unreal project.
> 
> This worked for me also, I never properly set up VS2022 with Unreal either so that may have something to do with it.

I think VS has the same function of installing the plugin into the engine or per project as Rider, the first time you open up a UE project. If you choose to install it into the engine, it will somehow causing the problem.

**Comment by mmmmmmmmmmmmmmmmmmmdonuts** [comment]
I managed to fix this without reinstalling everything! Not sure if this will work for everyone. It seems the visual studio plugins are what is interfering.
Steps I did:
1) go to the Unreal Engine folder (Currently UE 5.6) / Engine / Plugins
2) perform a search for rider* and visualstudio* and use the right click Open folder to find the plugins' root folders and delete them
3) open your unreal project in rider
4) open your .uproject file and make sure to delete all entries to rider and visual studio
5) go to settings | Languages and Frameworks | Unreal Engine |and now try to Install RiderLink in Engine 
and it finally worked!

**Comment by zjdaniels1985** [comment]
Seems this has been resolved? It didn't give me an error when using UE 5.7.1 and I just recnetly performed a clean install of Rider and built UE from source on Windows using VS 2022. I opted for it to be installed into the Engine Plugins directory and I didn't seem to have any issues during the build.
