### ISSUE TITLE
HElp，Failed to build RiderLink plugin at E:\UE_5.3."

### ISSUE THREAD

**Issue by hypoxiastars** [JetBrains/UnrealLink#278]
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Unversioned -Plugin=C:\Users\27149\AppData\Local\Temp\UnrealLink\Kiboxub\RiderLink.uplugin -Package=C:\Users\27149\AppData\Local\Temp\UnrealLink\Jirakaf
Initializing script modules...
Unhandled exception: System.Exception: Script module "E:\UE_5.3\Engine\Binaries\DotNET\AutomationTool\AutomationScripts\CookedEditor\CookedEditor.Automation.dll" not found for record "E:\UE_5.3\Engine\Intermediate\ScriptModules\CookedEditor.Automation.json"
   at UnrealBuildBase.CompileScriptModule.Build(RulesFileType RulesFileType, HashSet`1 FoundProjects, IEnumerable`1 BaseDirectories, IEnumerable`1 DefineConstants, BuildFlags BuildFlags, Boolean& bBuildSuccess, Action`1 OnBuildingProjects, ILogger Logger) in E:\UE_5.3\Engine\Source\Programs\Shared\EpicGames.Build\System\CompileScriptModules.cs:line 350
   at UnrealBuildBase.CompileScriptModule.InitializeScriptModules(RulesFileType RulesFileType, String ScriptsForProjectFileName, List`1 AdditionalScriptsFolders, Boolean bForceCompile, Boolean bNoCompile, Boolean bUseBuildRecords, Boolean& bBuildSuccess, Action`1 OnBuildingProjects, ILogger Logger) in E:\UE_5.3\Engine\Source\Programs\Shared\EpicGames.Build\System\CompileScriptModules.cs:line 196
   at AutomationToolDriver.Program.MainProc() in E:\UE_5.3\Engine\Source\Programs\AutomationTool\Program.cs:line 478
AutomationTool executed for 0h 0m 0s
AutomationTool exiting with ExitCode=1 (Error_Unknown)
BUILD FAILED
无法为 E:\UE_5.3 构建 RiderLink 插件
Failed to build RiderLink plugin

**Comment by linqen** [comment]
Same here, and I see there is a lot of people with this issue...

**Comment by linqen** [comment]
My workaround is (Unreal 5.3):

1. Settings -> Unreal Engine -> Extract Rider Link in Game
2. Compile game (so plugin gets compiled)
3. Cut the plugin from YourGameFolder -> Plugins -> Deverloper to -> F:\UE\UE_5.3\Engine\Plugins\Marketplace\Developer
4. Restart Rider

Looks like they have an issue in the way they tell the UnrealBuildTool to build the plugin, wrong parameters.

**Comment by omgAyane** [comment]
Getting the same thing in 5.4. Honestly have never had the rider plugin ever just be able to install after a fresh install of the ide. It either gives me this same error message or gets stuck at 73% when installing for hours. 
[idea.log](https://github.com/user-attachments/files/15849391/idea.log)

**Comment by DecoyRS** [comment]
@linqen unfortunately, we use officially provided tools by Epic Games and use their recommended arguments :(
Starting with UE 5.3+, UBT changed the way it processes and compiles managed dependencies (aka build.cs and target.cs files), but this issue doesn't look like it.

**Comment by DecoyRS** [comment]
@hypoxiastars what's your version of Rider?
Would you be so kind as to try verifying UE installation and trying again?
Epic Games Launcher > UE 5.3 >... > Verify
And try to install it once again?

**Comment by DecoyRS** [comment]
@omgAyane in your case, you get an internal compiler crash (the message should be visible in the RiderLink installation panel).
It's either:
* VS compiler ran out of memory (double check you have enough space on disk if swap enabled. Sometimes it's due to disk C is full)
* it's an actual problem with VS toolchain (there was a number of issues with UE not working with the latest builds of VS).
Make sure you have a correct VS installed for your version of UE:
https://dev.epicgames.com/documentation/en-us/unreal-engine/setting-up-visual-studio-development-environment-for-cplusplus-projects-in-unreal-engine?application_version=5.3

**Comment by omgAyane** [comment]
Oh interesting okay. I'm using ue5.4 and have VS2022 17.9.5. VS and Rider were both installed on my C drive. Which has 712gb free of 930gb.

**Comment by DecoyRS** [comment]
@omgAyane huh... Do you have swap enabled and what's your RAM size?
I used to see the message with VC internal crash all the time during UE4.20-4.22 era, but I thought it became much better lately. It was mostly because UE is trying to compile all the files in a single pass using Unity blobs, and we were working this around with decreasing the size of the blob.

**Comment by omgAyane** [comment]
64gb of RAM. Where can I check for the disk swap is enabled? Is that a page file thing?

**Comment by FiredPhoenixIR** [comment]
Same Issue :

Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Unversioned -Plugin=C:\Users\User\AppData\Local\Temp\UnrealLink\Sipofeg\RiderLink.uplugin -Package=C:\Users\User\AppData\Local\Temp\UnrealLink\Wybugaf
Initializing script modules...
Total script module initialization time: 0.09 s.
Using C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
Executing commands...
Copying 414 file(s) using max 64 thread(s)
Reading plugin from C:\Users\User\AppData\Local\Temp\UnrealLink\Wybugaf\HostProject\Plugins\RiderLink\RiderLink.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="C:\Users\User\AppData\Local\Temp\UnrealLink\Wybugaf\HostProject\HostProject.uproject" -plugin="C:\Users\User\AppData\Local\Temp\UnrealLink\Wybugaf\HostProject\Plugins\RiderLink\RiderLink.uplugin" -noubtmakefiles -manifest="C:\Users\User\AppData\Local\Temp\UnrealLink\Wybugaf\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\User\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\User\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt
Total execution time: 1.73 seconds
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type moduleType, ReadOnlyTargetRules targetRules, String& invalidReason) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1636
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3938
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3403
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1392
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, BuildConfiguration BuildConfiguration, ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1226
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in C:\Program Files\Epic Games\UE_5.4\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 660
Took 1.81s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\User\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 2s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
Failed to build RiderLink plugin for C:\Program Files\Epic Games\UE_5.4
Failed to build RiderLink plugin

**Comment by L1N337** [comment]
> 运行 AutomationTool...使用捆绑的 DotNet SDK 版本：6.0.302 启动 AutomationTool...解析命令行： BuildPlugin -Unversioned -Plugin=C：\Users\27149\AppData\Local\Temp\UnrealLink\Kiboxub\RiderLink.uplugin -Package=C：\Users\27149\AppData\Local\Temp\UnrealLink\Jirakaf 初始化脚本模块...未处理的异常：System.Exception：在 E：\UE_5.3\Engine\Source\Programs\Shared\ 中的 UnrealBuildBase.CompileScriptModule.Build（RulesFileType RulesFileType， HashSet1 BaseDirectories， IEnumerable1 OnBuildingProjects， ILogger Logger）的记录“E：\UE_5.3\Engine\Intermediate\ScriptModules\CookedEditor.Automation.json”找不到记录“E：\UE_5.3\Engine\Intermediate\ScriptModules\CookedEditor.Automation.dll”的脚本模块“E：\.3\Engine\Intermediate\ScriptModules\”E CompileScriptModules.cs：\UE_5.3\Engine\Source\Programs\AutomationTool\Program.cs：第478行的E：\.3\Engine\Source\Programs\Shared\EpicGames.Build\System\CompileScriptModules.cs的第19 UE_5 6行的UnrealBuildBase.CompileScriptModule.InitializeScriptModules（RulesFileType RulesFileType， String ScriptsForProjectFileName， List1 OnBuildingProjects， ILogger Logger）AutomationTool 执行了 0h 0m 0s AutomationTool 退出，ExitCode=1 （Error_Unknown） 构建失败 无法为 E：\UE_5.3 构建 RiderLink 插件 构建 RiderLink 插件失败`1 FoundProjects, IEnumerable``1 DefineConstants, BuildFlags BuildFlags, Boolean& bBuildSuccess, Action``1 AdditionalScriptsFolders, Boolean bForceCompile, Boolean bNoCompile, Boolean bUseBuildRecords, Boolean& bBuildSuccess, Action`

I also encountered this problem. I followed other people's attempts to re-download rider and ue or install from the engine to install from the game, but it didn't work.
My approach was to extract riderlink in the game and build the project before starting it. Then I could see the riderlink plugin was detected in ue. Extracting riderlink and building it seemed to be able to recapture it. I hope it will be helpful to those who come later.
By the way, I am using rider2024.3.6 and ue5.3.2

**Comment by tdellion** [comment]
im getting this as well.... freshly installed Unreal Engine, brand new Windows 11 install, freshly installed Visual Studio and following the instructions from Epics Visual Studio set up guide.  The Rider plug in fails to build...

**Comment by tdellion** [comment]
https://github.com/JetBrains/UnrealLink/issues/292#issuecomment-2899772846
