### ISSUE TITLE
Failed to generate project model definition files for the project file

### ISSUE THREAD

**Issue by Molinadev30** [JetBrains/UnrealLink#283]
Im using Rider with one project in Unreal Engine 5 and i got two error you can see in the picture
![imagen_2024-11-05_201757028](https://github.com/user-attachments/assets/30eda5cb-d6d4-4a3f-a983-d5707b95af9b)

Pressing show logs:
20:11:51.630: C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -ProjectFiles -Rider -Automated -Minimize -Platforms=Win64 -TargetTypes=Editor -TargetConfigurations=Development "C:\Users\ruben\OneDrive\Documentos\Unreal Projects\ToonTanks\ToonTanks.uproject"
20:11:51.892: Log file: C:\Users\ruben\AppData\Local\UnrealBuildTool\Log_GPF.txt
20:11:52.018: Generating Rider project files:
20:11:52.211: Available x64 toolchains (1):
20:11:52.211:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.211:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.211: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.217: Available x64 toolchains (1):
20:11:52.217:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.217:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.217: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.219: Available x64 toolchains (1):
20:11:52.219:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.219:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.219: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.220: Available x64 toolchains (1):
20:11:52.220:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.220:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.220: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.227: Available x64 toolchains (1):
20:11:52.227:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.227:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.227: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.230: Available x64 toolchains (1):
20:11:52.230:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.230:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.230: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.248: Writing project files...
20:11:52.248: Available x64 toolchains (1):
20:11:52.248:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.248:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.248: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.251: Available x64 toolchains (1):
20:11:52.251:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.251:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.251: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.615: Exception while generating include data for Target:UnrealEditor, Platform: Win64, Configuration: Development
20:11:52.624: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
20:11:52.624:    at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
20:11:52.624:    at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
20:11:52.624:    at UnrealBuildTool.ModuleRules.IsValidForTarget(Type moduleType, ReadOnlyTargetRules targetRules, String& invalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1636
20:11:52.624:    at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3938
20:11:52.624:    at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3403
20:11:52.625:    at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1392
20:11:52.625:    at UnrealBuildTool.RiderProjectFile.WriteProjectFile(List`1 InPlatforms, List`1 InConfigurations, PlatformProjectGeneratorCollection PlatformProjectGenerators, JsonWriterStyle Minimize, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\Rider\RiderProjectFile.cs:line 119
20:11:52.625: Available x64 toolchains (1):
20:11:52.625:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.625:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.625: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:52.626: Available x64 toolchains (1):
20:11:52.626:  * C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120
20:11:52.626:     (Family=14.41.34120, FamilyRank=5, Version=14.41.34123, Is64Bit=True, ReleaseChannel=Latest, Architecture=x64)
20:11:52.626: Visual Studio 2022 compiler version 14.41.34123 is not a preferred version. Please use the latest preferred version 14.38.33130
20:11:54.125: Writing project files... 100%
20:11:54.158: Total execution time: 2.48 seconds

I have tried lots of things without lucky

**Comment by Molinadev30** [comment]
![imagen_2024-11-05_202116915](https://github.com/user-attachments/assets/c78a5b17-9456-4349-af61-6a0b334c256a)
I received this nottification too
