### ISSUE TITLE
Failed to build RiderLink plugin for C:\Program Files\Epic Games\UE_5.4

### ISSUE THREAD

**Issue by iitaroki** [JetBrains/UnrealLink#286]
Hi,
I have this issue when making a new ue5 project and open rider for the first 
time it loads everything but gives me 3 errors,

-**First one is:** "Failed to generate project model definition files for 'Configuration: Development Editor, Platform: Win64"

-**Second one is**: "There are packages with vulnerabilities installed in this solution"

-**Third one** is the one am trying to fix and i think that the previous 2 errors are related to this one is Failed to build RiderLink plugin for C:\Program Files\Epic Games\UE_5.4.

Here is a detailed Log about the problem:

Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Unversioned -Plugin=C:\temp_folder\UnrealLink\Kisunes\RiderLink.uplugin -Package=C:\temp_folder\UnrealLink\Dodivop
Initializing script modules...
Total script module initialization time: 0.22 s.
Using C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
Executing commands...
Copying 414 file(s) using max 64 thread(s)
Reading plugin from C:\temp_folder\UnrealLink\Dodivop\HostProject\Plugins\RiderLink\RiderLink.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="C:\temp_folder\UnrealLink\Dodivop\HostProject\HostProject.uproject" -plugin="C:\temp_folder\UnrealLink\Dodivop\HostProject\Plugins\RiderLink\RiderLink.uplugin" -noubtmakefiles -manifest="C:\temp_folder\UnrealLink\Dodivop\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\tarok\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\tarok\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt
Total execution time: 3.80 seconds
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type moduleType, ReadOnlyTargetRules targetRules, String& invalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1636
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3938
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3403
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1392
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, BuildConfiguration BuildConfiguration, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1226
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 660
Took 3.94s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\tarok\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 4s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
Failed to build RiderLink plugin for C:\Program Files\Epic Games\UE_5.4
Failed to build RiderLink plugin

I REALLY HOPE THAT YOU CAN GIVE ME THE SOLUTION FOR THIS PROBLEM I TRIED EVERYTHING I CAN DO FROM VERIFYING THE UE5 ENGINE IN EPIC GAMES, CHECKING FOR THE VISUAL STUDIO THINGS IF DOWNLOAD CORRECTLY AND EVEN REINSTALLING RIDER.

**Comment by tychonaut** [comment]
I have the same issue and didn't find a solution or a proper workaround for installing the plugin into the engine folder. What worked, though, was extracting the plugin into the game folder and build the solution, which also builds the plugin. Hope this helps until a proper solution is available.
